# file-utils Self-Extracting Installer v0.3.0
# Generated by make_installer.ps1

# Your balanced installer content here...
# (This is where the full installer script would go)
Write-Host "This is a test installer script"
Write-Host "Archive size: 586.9 KB"
Write-Host "7za.exe size: 1296.5 KB"
Read-Host "Press Enter to exit test installer"
